"""
You are given two strings s and t.

String t is generated by random shuffling string s and then add one more letter at a random position.

Return the letter that was added to t.
"""
class Solution:
    def findTheDifference(self, s: str, t: str) -> str:
        mydict = {}
        for each in t:
            if each not in mydict:
                mydict[each] = 1
            else:
                mydict[each] += 1
        for each in mydict:
            if mydict[each] != s.count(each):
                return each